### ISSUE TITLE
tray not started on macos restart

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#108] opened 2022-01-21 14:34 UTC
After a successful installation on macos (onboarding + tray is running), when the machine is rebooted, tray is not starting. If the app icon is clicked to try starting the tray manually,  the on boarding process is showed again.

**Comment by gbraad** [comment] 2022-01-28 09:13
Starting of the tray is related to the wrong name used. This should be resolved.


> the on boarding process is showed again.

Otherwise a duplicate of #117, https://github.com/code-ready/crc/issues/2972
Issue with `crc setup --check-only`.

**Comment by gbraad** [comment] 2022-01-28 09:15
Keeping open until verified (accidently closed)

**Comment by anjannath** [comment] 2022-01-31 07:56
@adrianriobo with https://github.com/code-ready/crc/pull/2971 this is working for me, tray is auto started (shows the on-boarding screen, tray icon is not yet visible but will be after the on-boarding)

**Comment by adrianriobo** [comment] 2022-01-31 08:07
Ahh yeah just test it, not sure if it was some delay when I tested on Friday as I was not able to see the onboarding window, but you are totally right

**Comment by anjannath** [comment] 2022-01-31 09:13
fixed in https://github.com/code-ready/crc/pull/2971

**Closed as completed by anjannath** 2022-01-31 09:13 UTC
Labels: bug
